### ISSUE TITLE
Issues with keys in loops

### ISSUE THREAD

**Issue by alastairzotos** [frameable/el#3]
This is a cool project. I've just tried the todo list example and I've found that when adding a couple of items, randomly selecting some as "done" and then clicking "hide completed", the resulting list is incorrect, and the checkboxes aren't correctly checked too.

<img width="626" alt="image" src="https://user-images.githubusercontent.com/46943552/189523562-ce684dc3-9119-45e1-b381-ed0e3ba7daea.png">

<img width="626" alt="image" src="https://user-images.githubusercontent.com/46943552/189523585-60aa2072-2774-4c16-857d-82930eb93bc8.png">

**Comment by dchester** [comment]
Thanks -- looks like the resulting list is correct, but the checkbox `checked` property was out of sync.  Looking better now with version `0.7.3`
